
spring.application.name=demo


server.port=8080
#server.servlet.context-path=/oishi


app.greeting.message=Hello from config


spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springboot_demo
spring.datasource.username=root
spring.datasource.password=rootpwd123!!!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true